### ISSUE TITLE
Thanks for your solution, but I have issues

### ISSUE THREAD

**Issue by dimitri-ak** [Kevin-Bronsdijk/LogicAppsMonitoring#1]
Hi, Thanks for your solution. I tried to implement it, but I was not able to find release folder of the web job, also I tried to build it. And can't do it, to many errors during the build. Maybe you can give me a script for web job, so I won't need to work with build, because I am an admin, not developer :)

**Comment by Kevin-Bronsdijk** [comment]
Hi Dimitri thank you for your comment! Yes, you are right. I actually planned having a zipped version of the build output available, so it will be easy to consume for everyone without a full build environment. 

Unfortunately, I forgot to alter the .gitignore file which was restricting me from creating a folder called releases. This has been fixed and I've also added a link within the .readme as well.

Bit sloppy from my side, thanks for pointing this out. If you have any questions, please let me know.

**Comment by dimitri-ak** [comment]
Hi Kevin, finally I implemented your solution to my environment. It works! I am going to configure the alerts, and I have very good tool for monitoring all my logic apps. Thank you very much!
